# 腾讯云 SCF 云函数配置
component: scf
name: psychro-calculator-api

app: psychro-calculator
stage: prod

inputs:
  # 基本配置
  name: psychro-calculator-api
  src: 
    src: ./
    exclude:
      - .env
      - __pycache__
      - '*.pyc'
      - node_modules
      - .git
      - tests
      - .vscode
      - README.md
  handler: main_app.main
  runtime: Python3.9
  region: ap-guangzhou
  
  # 内存和超时配置 - 为计算密集型任务优化
  memorySize: 1024
  timeout: 30
  
  # 环境变量
  environment:
    variables:
      PYTHONPATH: /var/task
      TZ: Asia/Shanghai
      MATPLOTLIB_BACKEND: Agg
      
  # 触发器配置 - API网关
  events:
    - apigw:
        parameters:
          protocols:
            - https
            - http
          serviceName: psychro-calculator-api
          description: 焓湿图计算API服务
          environment: release
          endpoints:
            - path: /
              method: ANY
              enableCORS: true
              responseType: HTML
              serviceTimeout: 30
            - path: /{proxy+}
              method: ANY
              enableCORS: true
              responseType: HTML
              serviceTimeout: 30
          
  # VPC配置（如果需要访问内网资源）
  # vpc:
  #   vpcId: vpc-xxxxxxxx
  #   subnetId: subnet-xxxxxxxx
  
  # 预置并发配置（可选，用于减少冷启动）
  # provisionedConcurrencyConfig:
  #   provisionedConcurrencyNum: 1
    
  # 层配置（可选，用于共享依赖）
  # layers:
  #   - name: python-deps
  #     version: 1

  # 日志配置
  cls:
    logsetId: 
    topicId: 